<?php

namespace App\Core\ConsentForms\Requests;

use App\Core\ConsentForms\Models\ConsentForm;
use Illuminate\Foundation\Http\FormRequest;

class StoreConsentFormRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true; // Authorization handled in controller
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'contact_id' => 'required|exists:contacts,id',
            'consent_type' => [
                'required',
                'string',
                'in:' . implode(',', [
                    ConsentForm::TYPE_INITIAL_TREATMENT,
                    ConsentForm::TYPE_TELECONSULTATION,
                    ConsentForm::TYPE_MINORS,
                    ConsentForm::TYPE_RECORDING,
                    ConsentForm::TYPE_RESEARCH,
                    ConsentForm::TYPE_THIRD_PARTY_COMMUNICATION,
                    ConsentForm::TYPE_MEDICATION_REFERRAL,
                ]),
            ],
            'consent_title' => 'nullable|string|max:255',
            'consent_text' => 'nullable|string', // Will be generated by template if not provided
            
            // For minors
            'legal_guardian_name' => 'nullable|string|max:255|required_if:consent_type,minors',
            'legal_guardian_relationship' => 'nullable|string|max:100',
            'legal_guardian_id_document' => 'nullable|string|max:50',
            'minor_assent' => 'nullable|boolean',
            'minor_assent_details' => 'nullable|string',
            
            // Additional data for templates
            'treatment_duration' => 'nullable|string',
            'session_frequency' => 'nullable|string',
            'session_duration' => 'nullable|integer',
            'treatment_techniques' => 'nullable|array',
            'platform' => 'nullable|string|required_if:consent_type,teleconsultation',
            'security_info' => 'nullable|string',
            'recording_consent' => 'nullable|boolean',
        ];
    }

    /**
     * Get custom messages for validator errors.
     *
     * @return array<string, string>
     */
    public function messages(): array
    {
        return [
            'contact_id.required' => 'El paciente es requerido.',
            'contact_id.exists' => 'El paciente seleccionado no existe.',
            'consent_type.required' => 'El tipo de consentimiento es requerido.',
            'consent_type.in' => 'El tipo de consentimiento no es válido.',
            'legal_guardian_name.required_if' => 'El nombre del tutor es requerido para consentimientos de menores.',
            'platform.required_if' => 'La plataforma de videollamada es requerida para teleconsulta.',
        ];
    }
}

